language: python
python:
  - "2.7"

# setup database
before_install:
  # Build the Spatialite db backend
  - .travis/build_pysqlite2.sh
  - sudo apt-get install libspatialite-dev
  # Build the mysql 5.6 db backend  
  - .travis/install-mysql-5.6
  - mysql -e 'create database oipa_test COLLATE utf8_unicode_ci;'
  - sudo apt-get -q -y install binutils gdal-bin libgdal1h

# command to install dependencies
install:
  - "pip install -r OIPA/requirements.txt"
  - "pip install -r OIPA/test_requirements.txt"
  - "pip freeze -q"
  - "echo -e 'no\n' | OIPA/manage.py migrate --settings=OIPA.travis_test_settings" 
  - "echo -e 'no\n' | OIPA/manage.py migrate --database=mysql --settings=OIPA.travis_test_settings"

# create full text search indexes after running syncdb
before_script:
  - mysql oipa_test < .travis/create_fts_indexes.sql

# command to run tests
script: cd OIPA && coverage run --source=. --omit=*__init__*,*data_backup* -m py.test
after_success:
  - coveralls
