language: python
python:
  - "2.7"
sudo: false
addons:
  postgresql: "9.4"
services:
  - elasticsearch

cache:
  directories:
    - $HOME/.cache/pip

# command to install dependencies
install:
  - "pip install -r OIPA/requirements.txt"
  - "pip install -r OIPA/test_requirements.txt"

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - cd OIPA
  - python manage.py migrate --database=psql --settings=OIPA.test_settings
  - coverage run --source=. --omit=*__init__*,*data_backup* manage.py test --settings OIPA.test_settings --nomigrations
after_success:
  - coveralls
after_failure:
  - coveralls