# Docker Compose override file for OIPA development.
# Extends 'docker-compose.yml'.
#

version: "2"
services:

  postgres:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oipa
      - POSTGRES_USER=oipa
      - POSTGRES_PASSWORD=oipa
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data

  oipa:
    extends:
      file: docker-compose.yml
      service: oipa
    env_file:
      - etc/env/env.dev
    # command: ["/app/src/bin/wait-for-postgres.sh", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    # volumes:
    #   - .:/app/src
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  oipa-supervisor:
    extends:
      file: docker-compose.yml
      service: oipa-supervisor
    command: ["/app/src/bin/wait-for-postgres.sh", "--", "python", "manage.py", "supervisor"]
    env_file:
      - etc/env/env.dev
    volumes:
      - .:/app/src
    depends_on:
      - postgres
      - redis